"""
    Umweltbundesamt: Meeresumweltdatenbank (MUDAB)

    Meeres-Monitoringdaten von Küstenbundesländern und Forschungseinrichtungen   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.mudab.model.compartment import Compartment

from deutschland import mudab

globals()["Compartment"] = Compartment
from deutschland.mudab.model.parameter import Parameter


class TestParameter(unittest.TestCase):
    """Parameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParameter(self):
        """Test Parameter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Parameter()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
