"""
    Umweltbundesamt: Meeresumweltdatenbank (MUDAB)

    Meeres-Monitoringdaten von Küstenbundesländern und Forschungseinrichtungen   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.mudab.model.messstation import Messstation

from deutschland import mudab

globals()["Messstation"] = Messstation
from deutschland.mudab.model.list_mess_stationen200_response import (
    ListMessStationen200Response,
)


class TestListMessStationen200Response(unittest.TestCase):
    """ListMessStationen200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListMessStationen200Response(self):
        """Test ListMessStationen200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListMessStationen200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
