"""
    Umweltbundesamt: Meeresumweltdatenbank (MUDAB)

    Meeres-Monitoringdaten von Küstenbundesländern und Forschungseinrichtungen   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.mudab.model.messwert_plc import MesswertPLC

from deutschland import mudab


class TestMesswertPLC(unittest.TestCase):
    """MesswertPLC unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMesswertPLC(self):
        """Test MesswertPLC"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MesswertPLC()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
