"""
    Umweltbundesamt: Meeresumweltdatenbank (MUDAB)

    Meeres-Monitoringdaten von Küstenbundesländern und Forschungseinrichtungen   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.mudab.model.helcom_plc_station import HelcomPLCStation

from deutschland import mudab

globals()["HelcomPLCStation"] = HelcomPLCStation
from deutschland.mudab.model.inline_response2008 import InlineResponse2008


class TestInlineResponse2008(unittest.TestCase):
    """InlineResponse2008 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2008(self):
        """Test InlineResponse2008"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2008()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
