"""
    Umweltbundesamt: Meeresumweltdatenbank (MUDAB)

    Meeres-Monitoringdaten von Küstenbundesländern und Forschungseinrichtungen   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.mudab.model.project_station import ProjectStation

from deutschland import mudab

globals()["ProjectStation"] = ProjectStation
from deutschland.mudab.model.list_projekt_stationen200_response import (
    ListProjektStationen200Response,
)


class TestListProjektStationen200Response(unittest.TestCase):
    """ListProjektStationen200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListProjektStationen200Response(self):
        """Test ListProjektStationen200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListProjektStationen200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
