"""
Umweltbundesamt: Meeresumweltdatenbank (MUDAB)

Meeres-Monitoringdaten von Küstenbundesländern und Forschungseinrichtungen   # noqa: E501

The version of the OpenAPI document: 1.0.0
Contact: kontakt@bund.dev
Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.mudab.model.parameter_plc import ParameterPLC

from deutschland import mudab

globals()["ParameterPLC"] = ParameterPLC
from deutschland.mudab.model.list_parameters_plc200_response import (
    ListParametersPlc200Response,
)


class TestListParametersPlc200Response(unittest.TestCase):
    """ListParametersPlc200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListParametersPlc200Response(self):
        """Test ListParametersPlc200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListParametersPlc200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
