"""
    Umweltbundesamt: Meeresumweltdatenbank (MUDAB)

    Meeres-Monitoringdaten von Küstenbundesländern und Forschungseinrichtungen   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.mudab.model.compartment import Compartment

from deutschland import mudab

globals()["Compartment"] = Compartment
from deutschland.mudab.model.messstation import Messstation


class TestMessstation(unittest.TestCase):
    """Messstation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessstation(self):
        """Test Messstation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Messstation()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
