"""
Umweltbundesamt: Meeresumweltdatenbank (MUDAB)

Meeres-Monitoringdaten von Küstenbundesländern und Forschungseinrichtungen   # noqa: E501

The version of the OpenAPI document: 1.0.0
Contact: kontakt@bund.dev
Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.mudab.model.filter_action import FilterAction

from deutschland import mudab


class TestFilterAction(unittest.TestCase):
    """FilterAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilterAction(self):
        """Test FilterAction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FilterAction()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
