"""
    Umweltbundesamt: Meeresumweltdatenbank (MUDAB)

    Meeres-Monitoringdaten von Küstenbundesländern und Forschungseinrichtungen   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.mudab.model.messwert_plc import MesswertPLC

from deutschland import mudab

globals()["MesswertPLC"] = MesswertPLC
from deutschland.mudab.model.list_messwerte_plc200_response import (
    ListMesswertePlc200Response,
)


class TestListMesswertePlc200Response(unittest.TestCase):
    """ListMesswertePlc200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListMesswertePlc200Response(self):
        """Test ListMesswertePlc200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListMesswertePlc200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
