"""
Umweltbundesamt: Meeresumweltdatenbank (MUDAB)

Meeres-Monitoringdaten von Küstenbundesländern und Forschungseinrichtungen   # noqa: E501

The version of the OpenAPI document: 1.0.0
Contact: kontakt@bund.dev
Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.mudab.model.parameter_value import ParameterValue

from deutschland import mudab


class TestParameterValue(unittest.TestCase):
    """ParameterValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParameterValue(self):
        """Test ParameterValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ParameterValue()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
