"""
    Umweltbundesamt: Meeresumweltdatenbank (MUDAB)

    Meeres-Monitoringdaten von Küstenbundesländern und Forschungseinrichtungen   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.mudab.model.parameter_plc import ParameterPLC

from deutschland import mudab


class TestParameterPLC(unittest.TestCase):
    """ParameterPLC unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParameterPLC(self):
        """Test ParameterPLC"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ParameterPLC()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
