"""
Umweltbundesamt: Meeresumweltdatenbank (MUDAB)

Meeres-Monitoringdaten von Küstenbundesländern und Forschungseinrichtungen   # noqa: E501

The version of the OpenAPI document: 1.0.0
Contact: kontakt@bund.dev
Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.mudab.model.helcom_plc_station import HelcomPLCStation

from deutschland import mudab

globals()["HelcomPLCStation"] = HelcomPLCStation
from deutschland.mudab.model.list_plc_stations200_response import (
    ListPlcStations200Response,
)


class TestListPlcStations200Response(unittest.TestCase):
    """ListPlcStations200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListPlcStations200Response(self):
        """Test ListPlcStations200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListPlcStations200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
